version: '3.4'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "6432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on: 
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  parkings.api:
    image: ${DOCKER_REGISTRY-}parkingsapi
    build:
      context: .
      dockerfile: Parkings.API/Dockerfile
    depends_on: 
      - db

volumes:
  local_pgdata:
  pgadmin-data: