version: '3.4'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "6432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - backend
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on: 
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - backend

  parkings.api:
    image: ${DOCKER_REGISTRY-}parkingsapi
    build:
      context: .
      dockerfile: services/Parkings/Parkings.API/Dockerfile
    depends_on: 
      - db
    networks:
      - backend

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: infra/ApiGateways/ApiGateway/Dockerfile
    ports:
      - 8001:80
    networks:
      - backend

  accounts.api:
    image: ${DOCKER_REGISTRY-}accountsapi
    build:
      context: .
      dockerfile: services/Account/Accounts.API/Dockerfile
    networks:
      - backend

volumes:
  local_pgdata:
  pgadmin-data:
  
networks:
  backend:    
